# syntax=docker/dockerfile:1.5

ARG APP_IMAGE=ghcr.io/novarg93/photo-guide-belgorod:app-latest

FROM ${APP_IMAGE} AS app

FROM nginx:alpine

# public из app-образа
COPY --from=app /var/www/public /var/www/public

# nginx config
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf